---
# ItemCommands configuration file
# Developed by TheAz928

# If the item should be removed after usage
settings:
  remove-items: true

# Format:
# "ID:DAMAGE":
#    runAs: player/console/asop
#    commands:
#      - " "
#      - " "
#    name: test
#    lore:
#      - " "
# TAGS:
# {name} - Player name
# {tag} - Player Name tag
# {level} - Player world name
# {x} - Player x
# {y} - Player y
# {z} - Player z
# we perfer using 2 as console
# RUN_AS:
#    0 - player
#    1 - op
#    2 - console
"0:0":
  name: ""
  lore:
    - ""
  runAs: 2
  commands:
    - ""
    "0:0":
  name: ""
  lore:
    - ""
  runAs: 2
  commands:
    - """0:0":
  name: ""
  lore:
    - ""
  runAs: 2
  commands:
    - ""
    "0:0":
  name: ""
  lore:
    - ""
  runAs: 2
  commands:
    - ""
    "0:0":
  name: ""
  lore:
    - ""
  runAs: 2
  commands:
    - ""
    "0:0":
  name: ""
  lore:
    - ""
  runAs: 2
  commands:
    - ""
    "0:0":
  name: ""
  lore:
    - ""
  runAs: 2
  commands:
    - ""
    "0:0":
  name: ""
  lore:
    - ""
  runAs: 2
  commands:
    - ""
    "0:0":
  name: ""
  lore:
    - ""
  runAs: 2
  commands:
    - ""
    "0:0":
  name: ""
  lore:
    - ""
  runAs: 2
  commands:
    - ""
    "0:0":
  name: ""
  lore:
    - ""
  runAs: 2
  commands:
    - ""
  "0:0":
  name: ""
  lore:
    - ""
  runAs: 2
  commands:
    - ""  
  "0:0":
  name: ""
  lore:
    - ""
  runAs: 2
  commands:
    - ""  
 "0:0":
  name: ""
  lore:
    - ""
  runAs: 2
  commands:
    - ""   
   "0:0":
  name: ""
  lore:
    - ""
  runAs: 2
  commands:
    - "" 
...
